### ISSUE TITLE
addListener?

### ISSUE THREAD

**Issue by domenic** [PolymerLabs/virtual-list#11]
https://github.com/PolymerLabs/virtual-list/blob/design/DESIGN.md#layout has a method named `addListener`.

Is this just a typo, and it should be `addEventListener`? Or did we invent a new evening system? We definitely don't want to be shipping a second eventing system with the browser, so if it's the latter, please move to inheriting from `EventTarget` and using the standard eventing system instead.

**Comment by valdrinkoshi** [comment]
Agreed, these should be renamed to `add/removeEventListener` and the event names should be more descriptive. Would these work?
```
position -> children-position-changed
range -> range-changed
size -> scroll-size-changed
scrollError -> scroll-error-changed
```

**Comment by domenic** [comment]
I don't think it's a simple matter of renaming. You need to actually use the platform's `EventTarget` class via inheritance.

Even names on the platform don't use hyphens, and generally use present tense. So it'd be childrenpositionchange; rangechange; scrollsizechange; scrollerrorchange.
